include:
- template: Terraform/Base.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Terraform/Base.gitlab-ci.yml
- template: Jobs/SAST-IaC.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Jobs/SAST-IaC.gitlab-ci.yml

image:
  name: "$CI_TEMPLATE_REGISTRY_HOST/gitlab-org/terraform-images/releases/1.5:v1.4.0"

stages:
  - auth
  - validate
  - test
  - build
  - deploy
  - cleanup

variables:
  SANDBOX_EG_ENABLED: "true"

assume_role_and_deploy:
  stage: auth
  image: amazon/aws-cli
  script:
    - ASSUMED_ROLE=$(aws sts assume-role --role-arn arn:aws:iam::030588431668:role/gitlab_sandbox_tf --role-session-name example)
    - export AWS_ACCESS_KEY_ID=$(echo $ASSUMED_ROLE | jq -r '.Credentials.AccessKeyId')
    - export AWS_SECRET_ACCESS_KEY=$(echo $ASSUMED_ROLE | jq -r '.Credentials.SecretAccessKey')
    - export AWS_SESSION_TOKEN=$(echo $ASSUMED_ROLE | jq -r '.Credentials.SessionToken')
    - echo "AWS Credentials set for this job."
  artifacts:
    reports:
      dotenv: aws_credentials.env

.terraform:build:
  dependencies:
    - assume_role_and_deploy
